// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcJQH5L4q8fkG0aHZZo4g64SG9Titvig',
    appId: '1:402610814588:web:cee375eb98a879d28693f9',
    messagingSenderId: '402610814588',
    projectId: 'edumanage-1b145',
    authDomain: 'edumanage-1b145.firebaseapp.com',
    storageBucket: 'edumanage-1b145.firebasestorage.app',
    measurementId: 'G-2S3FERNPTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdhkkXybv91x6kox4bJdFRokdR9DvVHw',
    appId: '1:402610814588:android:c0ca15d185baad8d8693f9',
    messagingSenderId: '402610814588',
    projectId: 'edumanage-1b145',
    storageBucket: 'edumanage-1b145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDewwospMsIDC7visCjVHpillU6fXVXoO8',
    appId: '1:402610814588:ios:1c19c3e4f4db7cd48693f9',
    messagingSenderId: '402610814588',
    projectId: 'edumanage-1b145',
    storageBucket: 'edumanage-1b145.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDewwospMsIDC7visCjVHpillU6fXVXoO8',
    appId: '1:402610814588:ios:1c19c3e4f4db7cd48693f9',
    messagingSenderId: '402610814588',
    projectId: 'edumanage-1b145',
    storageBucket: 'edumanage-1b145.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHcJQH5L4q8fkG0aHZZo4g64SG9Titvig',
    appId: '1:402610814588:web:db6bbc5ee44a69c98693f9',
    messagingSenderId: '402610814588',
    projectId: 'edumanage-1b145',
    authDomain: 'edumanage-1b145.firebaseapp.com',
    storageBucket: 'edumanage-1b145.firebasestorage.app',
    measurementId: 'G-J3L6L1RP9W',
  );
}
